version: '3'
services:
  node1:
    build: .
    container_name: node1
    environment:
      - NODE_NAME=node 1
      - NODE_URL=http://node1:3000
    ports:
      - "3000:3000"
  node2:
    build: .
    container_name: node2
    environment:
      - NODE_NAME=node 2
      - NODE_URL=http://node2:3002
      - SEED_NODE_URLS=http://localhost:3000
    ports:
      - "3002:3000"
  node3:
    build: .
    container_name: node3
    environment:
      - NODE_NAME=node 3
      - NODE_URL=http://node3:3003
      - SEED_NODE_URLS=http://localhost:3000
    ports:
      - "3003:3000"
  node4:
    build: .
    container_name: node4
    environment:
      - NODE_NAME=node 4
      - NODE_URL=http://node4:3004
      - SEED_NODE_URLS=http://localhost:3000
    ports:
      - "3004:3000"
  node5:
    build: .
    container_name: node5
    environment:
      - NODE_NAME=node 5
      - NODE_URL=http://node5:3005
      - SEED_NODE_URLS=http://localhost:3000
    ports:
      - "3005:3000"

networks:
  node-network:
    driver: bridge
